export const TRANSFER_BALANCE = "TRANSFER_BALANCE";
export const ADD_USER_INFO = "ADD_USER_INFO";
export const RE_AUTHENTICATE = "RE_AUTHENTICATE";
export const CHECK_USER_INFO = "CHECK_USER_INFO";
export const SET_LOADING = "SET_LOADING";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_TRANSACTION = "ADD TRANSACTION";
